### ISSUE TITLE
TILER2Plugin dependency but no trace of it in the package on thunderstore

### ISSUE THREAD

**Issue by xiaoxiao921** [SirHamburger/ArtifactOfDoom#1]
Hi. Looks awesome for a first mod !
You have a TILER2Plugin dependency in the code. But no trace of it in the package you uploaded on thunderstore.io
The mod will fail to install on all mod managers and only experienced users will know that'll they need to download TILER2 manually after the error show up in the console
We also have a modding discord available. If you have issue with anything we'll be happy to help
https://discord.gg/5MbXZvd

**Comment by SirHamburger** [comment]
Thank you very much for your feedback. 
Do i just have to reupload it with the inserted dependency under a new version in thunderstore?

**Comment by SirHamburger** [comment]
New version (0.8.1) with the updated dependency
