### ISSUE TITLE
typo in artifact description

### ISSUE THREAD

**Issue by breadguyyy** [SirHamburger/ArtifactOfDoom#3]
it says "you get items on enemy kills but _loose_ items every time you take damage." it should say "lose" :)
also may I suggest a new description that might sound better: "Players have a chance to gain items after defeating monsters, but may lose items upon taking damage."
cool mod btw! :D

**Comment by SirHamburger** [comment]
Thank you very much for the feedback. I'm not a nativ english speaker so there will be many typing mistakes. But i will change it with the next release.
And nice that you enjoy the mod. 

If you've any issues or new typos feel free to open a new issue or contact me in discord
