### ISSUE TITLE
ArtifactOfDoomUI class registers as an independent mod

### ISSUE THREAD

**Issue by wooffet** [SirHamburger/ArtifactOfDoom#5]
The ArtifactOfDoomUI class uses attributes to register as an independent mod, which means it loads separately when starting the game. It is also registering with the name `UI Modifier` and guid `com.ohway.UIMod` which is incorrect as this isn't the ArtifactOfDoom mod.

Current class attributes:

```C#
[R2API.Utils.R2APISubmoduleDependency("ResourcesAPI")]
[BepInPlugin("com.ohway.UIMod", "UI Modifier", "1.0")]
[BepInDependency(MiniRpcPlugin.Dependency)]
public class ArtifactOfDoomUI : BaseUnityPlugin
{
...
```

Recommended class attributes: None, see below:

```C#
public class ArtifactOfDoomUI : BaseUnityPlugin
{
...
```

This would require loading the UI code in a different way to how it works currently. I did have something for this but I seem to have lost that piece of work - I'll respond to this issue if I get something that works again.

**Comment by SirHamburger** [comment]
Closed with last commit
